-- ============================================
-- Supabase 统计系统初始化脚本（推荐给新项目 / Fork 用户）
-- ============================================
-- 使用方式：
-- 1. 在 Supabase SQL Editor 中整段执行
-- 2. 执行成功后即可直接配合前端使用
-- 3. 本脚本不包含旧结构迁移逻辑，主打简单上手
-- 4. 时间字段统一使用 TIMESTAMPTZ，查询展示时请使用
--    AT TIME ZONE 'Asia/Shanghai' + to_char(...)
-- ============================================

-- 1. 主表：聚合统计表
CREATE TABLE IF NOT EXISTS public.image_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_id TEXT NOT NULL UNIQUE CHECK (btrim(image_id) <> ''),
  series TEXT NOT NULL CHECK (series IN ('desktop', 'mobile', 'avatar', 'video', 'bing')),
  category TEXT,
  total_views INT NOT NULL DEFAULT 0 CHECK (total_views >= 0),
  total_downloads INT NOT NULL DEFAULT 0 CHECK (total_downloads >= 0),
  last_viewed_at TIMESTAMPTZ,
  last_downloaded_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.image_stats IS
'当前统计主表。前端通过 RPC 写入，GitHub Actions 通过 get_hot_stats 导出热门统计。';

-- 2. 索引
CREATE INDEX IF NOT EXISTS idx_image_stats_image_id
  ON public.image_stats(image_id);

CREATE INDEX IF NOT EXISTS idx_image_stats_series
  ON public.image_stats(series);

CREATE INDEX IF NOT EXISTS idx_image_stats_series_views
  ON public.image_stats(series, total_views DESC);

CREATE INDEX IF NOT EXISTS idx_image_stats_series_downloads
  ON public.image_stats(series, total_downloads DESC);

CREATE INDEX IF NOT EXISTS idx_image_stats_updated_at
  ON public.image_stats(updated_at DESC);

-- 3. RLS
ALTER TABLE public.image_stats ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anonymous read" ON public.image_stats;
CREATE POLICY "Allow anonymous read"
  ON public.image_stats
  FOR SELECT
  USING (true);

-- 4. 浏览计数 RPC
CREATE OR REPLACE FUNCTION public.increment_view(
  img_id TEXT,
  series_name TEXT,
  cat TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.image_stats (
    image_id,
    series,
    category,
    total_views,
    last_viewed_at,
    updated_at
  )
  VALUES (
    img_id,
    series_name,
    cat,
    1,
    NOW(),
    NOW()
  )
  ON CONFLICT (image_id) DO UPDATE SET
    total_views = public.image_stats.total_views + 1,
    last_viewed_at = NOW(),
    updated_at = NOW();
END;
$$;

COMMENT ON FUNCTION public.increment_view(TEXT, TEXT, TEXT) IS
'浏览量 +1。前端打开壁纸详情时调用。';

-- 5. 下载计数 RPC
CREATE OR REPLACE FUNCTION public.increment_download(
  img_id TEXT,
  series_name TEXT,
  cat TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.image_stats (
    image_id,
    series,
    category,
    total_views,
    total_downloads,
    last_downloaded_at,
    updated_at
  )
  VALUES (
    img_id,
    series_name,
    cat,
    0,
    1,
    NOW(),
    NOW()
  )
  ON CONFLICT (image_id) DO UPDATE SET
    total_downloads = public.image_stats.total_downloads + 1,
    last_downloaded_at = NOW(),
    updated_at = NOW();
END;
$$;

COMMENT ON FUNCTION public.increment_download(TEXT, TEXT, TEXT) IS
'下载量 +1。前端点击下载按钮时调用。';

-- 6. 热门统计导出 RPC
CREATE OR REPLACE FUNCTION public.get_hot_stats(
  series_filter TEXT,
  limit_count INT DEFAULT 500
)
RETURNS TABLE (
  image_id TEXT,
  total_views INT,
  total_downloads INT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    i.image_id,
    i.total_views,
    i.total_downloads
  FROM public.image_stats i
  WHERE i.series = series_filter
  ORDER BY i.total_views DESC, i.total_downloads DESC, i.image_id ASC
  LIMIT limit_count;
END;
$$;

COMMENT ON FUNCTION public.get_hot_stats(TEXT, INT) IS
'导出某个系列的热门统计，供 scripts/export-stats.js 调用。';

-- 7. 验证
SELECT
  COUNT(*) AS image_count
FROM public.image_stats;

-- 8. 查询示例（北京时间展示）
-- 查看最近更新的统计记录
-- SELECT
--   image_id,
--   series,
--   total_views,
--   total_downloads,
--   to_char(updated_at AT TIME ZONE 'Asia/Shanghai', 'YYYY-MM-DD HH24:MI:SS') AS updated_at_cn,
--   to_char(last_viewed_at AT TIME ZONE 'Asia/Shanghai', 'YYYY-MM-DD HH24:MI:SS') AS last_viewed_at_cn,
--   to_char(last_downloaded_at AT TIME ZONE 'Asia/Shanghai', 'YYYY-MM-DD HH24:MI:SS') AS last_downloaded_at_cn
-- FROM public.image_stats
-- ORDER BY updated_at DESC
-- LIMIT 20;
